// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let fibonacci = (num) => {
  if (num <= 1) return 1;
  return fibonacci(num - 1) + fibonacci(num - 2);
}

let findEvenSum = (maxLimit) => {
  let sum = 0;
  let index = 1;
  while (fibonacci(index) < maxLimit) {
    index++;
    if (fibonacci(index) % 2 === 0) sum += fibonacci(index)
  }
  return sum;
}

let fourMillion = findEvenSum(4000000)
console.log(fourMillion)
